### ISSUE TITLE
Trouble installing CFFI module

### ISSUE THREAD

**Issue by DevoDon** [spatialaudio/python-sounddevice#107]
```
C:\WINDOWS\system32>py -m pip install cffi --user
Collecting cffi
  Using cached cffi-1.11.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Dale\AppData\Local\Temp\pip-build-z8xjfkhv\cffi\setup.py", line 116, in <module>
        if sys.platform == 'win32' and uses_msvc():
      File "C:\Users\Dale\AppData\Local\Temp\pip-build-z8xjfkhv\cffi\setup.py", line 94, in uses_msvc
        return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
      File "C:\Program Files\Python37\lib\distutils\command\config.py", line 227, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Program Files\Python37\lib\distutils\command\config.py", line 133, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "C:\Program Files\Python37\lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "C:\Program Files\Python37\lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Program Files\Python37\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Program Files\Python37\lib\site-packages\setuptools\msvc.py", line 1228, in return_env
        [self.VCIncludes,
      File "C:\Program Files\Python37\lib\site-packages\setuptools\msvc.py", line 877, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "C:\Program Files\Python37\lib\site-packages\setuptools\msvc.py", line 556, in VCInstallDir
        raise distutils.errors.DistutilsPlatformError(msg)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Dale\AppData\Local\Temp\pip-build-z8xjfkhv\cffi\
```

**Comment by tgarc** [comment]
That's odd, you shouldn't need a compiler at all for cffi unless you actually are compiling an extension. But shouldn't you be asking the cffi people about this? Here's their issue tracker:

https://bitbucket.org/cffi/cffi/issues

**Comment by tgarc** [comment]
I just encountered a similar error

```distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).```

on a fresh windows install. try upgrading pip, that fixed it for me:

pip install --upgrade pip

**Comment by mgeier** [comment]
@DevoDon Did upgrading `pip` fix the problem for you?
