### ISSUE TITLE
AttributeError: module 'sounddevice' has no attribute 'rec'

### ISSUE THREAD

**Issue by devxpy** [spatialaudio/python-sounddevice#121]
```
Python 3.6.4 (default, Feb 19 2018, 19:54:22) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sounddevice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/Stuff/Projekt/iwatkie/sounddevice.py", line 5, in <module>
    myrecording = sd.rec(int(5 * fs), channels=2)
AttributeError: module 'sounddevice' has no attribute 'rec'
```
```
$ pip freeze
cffi==1.11.4
numpy==1.14.1
pycparser==2.18
sounddevice==0.3.10
```
i am using pyenv

**Comment by tgarc** [comment]
It looks like you may have saved your own script as sounddevice.py and launched python in the same directory that its located thus importing your own script instead of sounddevice

**Comment by devxpy** [comment]
I feel very stupid now

**Comment by tgarc** [comment]
LOL happens to the best of us
