### ISSUE TITLE
ModuleNotFoundError: No module named '_sounddevice_data'

### ISSUE THREAD

**Issue by sprocket1** [spatialaudio/python-sounddevice#137]
Hi, I'm very new to Python and Spyder. 
I'm getting this on the Spyder console, seems related to #110 but I'm not sure what to make of it.

import sounddevice as sd
Traceback (most recent call last):

  File "<ipython-input-1-1b8d9fe8fdfa>", line 1, in <module>
    import sounddevice as sd

  File "C:\Users\James\Anaconda3\lib\site-packages\sounddevice.py", line 73, in <module>
    import _sounddevice_data

ModuleNotFoundError: No module named '_sounddevice_data'

**Comment by sprocket1** [comment]
I should add that I've done this on two separate Win7 machines, one 64bit and one 32bit. I get the same result on both.

**Comment by mgeier** [comment]
OK, this should be fixed in #122, but I haven't made a new release since then, therefore it isn't available on `conda-forge` yet, either.

I'll make a release in the next few days, and hopefully soon afterwards this will also be available on `conda-forge`.

In the meantime, you should try to install the `sounddevice` module with `pip`, which should work fine.
Note that it is no problem to use `pip` within a `conda` environment.

If you are having troubles installing, don't hesitate to ask for help here.

**Comment by sprocket1** [comment]
Thank you so much. That seems to have worked. Now the fund begins...

**Comment by mgeier** [comment]
An automatic update on `conda-forge` is in progress, but there seems to be a minor problem keeping it from finishing: https://github.com/conda-forge/python-sounddevice-feedstock/pull/1.
If anybody knows how to solve this, please do!

**Comment by mgeier** [comment]
Version 3.11 is now on `conda-forge`.

@sprocket1 Can you please if it works for you?

**Comment by 74HC14** [comment]
I've just tried running sounddevice in Spyder on macOS and got an identical issue with 0.3.11 as installed through conda-forge.

**Comment by mgeier** [comment]
@74HC14 Thanks for checking this out. On macOS, there is a different problem: the dependency `portaudio` (https://anaconda.org/conda-forge/portaudio) doesn't seem to be available for macOS on the `conda-forge` channel, or is it?
Do you get an error/warning message on installation?

It seems to be available in the `anaconda` channel (https://anaconda.org/anaconda/portaudio), was this package installed in your case?

**Comment by 74HC14** [comment]
Ah, that looks like that was probably the problem. I've just run it through pip now without a hitch, thanks for the quick reply.

**Comment by mgeier** [comment]
@74HC14 Did you check if the `portaudio` package from the `anaconda` channel gets installed in your case?

I've just created #144 for trying to load the dylib from anaconda, but I cannot test it because I don't have a Mac.
Does this work for you (by not using the dylib installed by `pip`)?
You can simply try to add this one line by hand: https://github.com/spatialaudio/python-sounddevice/pull/144/files

See also #122.

**Comment by 74HC14** [comment]
Just uninstalled sounddevice by pip and reinstalled via `conda install -c conda-forge python-sounddevice`. Running `conda list` has rows of both
`portaudio                 19.6.0               h41429eb_1`
along with the
`python-sounddevice        0.3.11                     py_0    conda-forge`
and I still get the error.

Portaudio is still present after uninstalling the conda sounddevice.

**Comment by mgeier** [comment]
@74HC14 Thanks for testing! So the `portaudio` package seems to get installed automatically, even though it doesn't exist (for macOS) in the `conda-forge` channel. Or did you install the `portaudio` package before?

It is still not expected to work unless you apply the one-line change from #144!

**Comment by 74HC14** [comment]
Going back through terminal's history doesn't come up with any installs of portaudio so I'm pretty sure it was already in there, presumably bundled with Anaconda's default modules.

**Comment by mgeier** [comment]
@74HC14 Did you try if the change from #144 works for you?

To determine which file was actually loaded, please provide the value of `sounddevice._libname`.

**Comment by sprocket1** [comment]
Sorry for the late reply. I just now tried
conda install sounddevice
from my base environment (python 3.6.4) and it did not work.

I then created a new environment (for other reasons) based on python 3.5.5 and tried that again. Again, it did not work. It did work with pip install.

James May
Principal Sprocketeer
Audio Sprockets, LLC
200 Coyote St. #2674
Nevada City, CA 95959
530-362-8891
www.audiosprockets.com

**Comment by mgeier** [comment]
@sprocket1 Is there an error message?

**Comment by sprocket1** [comment]
C:\Users\James\Dropbox\Python files\UTP>conda install sounddevice
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - sounddevice

Current channels:

  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
  - https://conda.anaconda.org/anaconda/win-32
  - https://conda.anaconda.org/anaconda/noarch

James May
Principal Sprocketeer
Audio Sprockets, LLC
200 Coyote St. #2674
Nevada City, CA 95959
530-362-8891
www.audiosprockets.com

**Comment by sprocket1** [comment]
Matthias,
Sorry about that, I have been distracted. That command worked just fine!

I want to thank you for developing sounddevice. It really is a great utility, and has enabled me to get my application built with a minimum of hassle.

On that note, I have a related question for you. I am looking for help in packaging my Python app into an self contained exe app for Windows. I’ve been struggling with Pyinstaller, Py2Exe and cx_freeze. All those tools seem to be broken for moderate to complex apps. I can give more specifics, but first I would just as if you know someone who might be able to help? This would be paid worked.

James May
Principal Sprocketeer
Audio Sprockets, LLC
200 Coyote St. #2674
Nevada City, CA 95959
530-362-8891
www.audiosprockets.com

**Comment by mgeier** [comment]
@sprocket1 I'm glad that it works now for you! And thanks for the praise!

I'm sorry, but I have no experience with any of the Python-bundling-tools and I don't know anyone who has.
The only related discussion here was #130.

If you find out any ways how to make the `sounddevice` module work better with those tools, please let me know!

**Comment by sprocket1** [comment]
FYI, yesterday I had success using Pynsist to create a bundled installer that makes an independent python installation with all the project dependencies in the user’s directory of choice, regardless of whether they already have Python installed on their computer or not. That serves my needs for now, and the process was relatively painless.

James May
Principal Sprocketeer
Audio Sprockets, LLC
200 Coyote St. #2674
Nevada City, CA 95959
530-362-8891
www.audiosprockets.com

**Comment by regallasandeepkumarreddy** [comment]
import sounddevice
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\sounddevice.py", line 80, in <module>
    import _sounddevice_data
ModuleNotFoundError: No module named '_sounddevice_data'


still facing the issue  - tried pip install sounddevice

**Comment by DeepanshuXio** [comment]
I am also facing the exact same issue. Tried above answers but still No Luck. 
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deepanshumehta/Desktop/QEAutomation/APP_Automation/conftest.py", line 3, in <module>
    from APP_Automation.utils.allutils import *
  File "/Users/deepanshumehta/Desktop/QEAutomation/APP_Automation/utils/allutils.py", line 22, in <module>
    import sounddevice as sd
  File "/Users/deepanshumehta/.pyenv/versions/appium/lib/python3.9/site-packages/sounddevice.py", line 80, in <module>
    import _sounddevice_data
ModuleNotFoundError: No module named '_sounddevice_data'

**Comment by mgeier** [comment]
If there are still problems, please create a new issue providing the information mentioned in https://python-sounddevice.readthedocs.io/en/0.4.6/CONTRIBUTING.html#reporting-problems

And please mention what exactly you tried and what exactly happened. Simply saying "Tried above answers but still No Luck" doesn't really help. Be more specific!
