### ISSUE TITLE
Cannot import on Anaconda/macOS

### ISSUE THREAD

**Issue by sammosummo** [spatialaudio/python-sounddevice#165]
Using the latest Miniconda on macOS, everything up-to-date. Tried to install via `pip install sounddevice`. Installed successfully, but `import sounddevice as sd` yields

```
Traceback (most recent call last):
  File "/Users/sam/PycharmProjects/Charlie3/charlie3/sound/synthesis.py", line 581, in <module>
    test()
  File "/Users/sam/PycharmProjects/Charlie3/charlie3/sound/synthesis.py", line 449, in test
    sound.play(False)
  File "/Users/sam/PycharmProjects/Charlie3/charlie3/sound/synthesis.py", line 434, in play
    self._backend_module.play_wait(self._obj)
  File "/Users/sam/PycharmProjects/Charlie3/charlie3/sound/synthesis.py", line 404, in _backend_module
    return import_module(f"charlie3.sound._{self.backend}")
  File "/Users/sam/miniconda3/envs/loocius/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sam/PycharmProjects/Charlie3/charlie3/sound/_sounddevice.py", line 8, in <module>
    import sounddevice as sd
  File "/Users/sam/miniconda3/envs/loocius/lib/python3.7/site-packages/sounddevice.py", line 58, in <module>
    from _sounddevice import ffi as _ffi
ImportError: cannot import name 'ffi' from '_sounddevice' (/Users/sam/PycharmProjects/Charlie3/charlie3/sound/_sounddevice.py)
```

I get the same error when I try to reinstall using the `conda-forge` method.

**Comment by mgeier** [comment]
Thanks for the report!

Did you create the file `/Users/sam/PycharmProjects/Charlie3/charlie3/sound/_sounddevice.py`?

The problem seems to be that the `sounddevice` module looks for a file `_sounddevice.py`, which is part of the package. But since you have a local file with the same name, Python cannot find the right one ...

The solution should be to rename your file to something different.

**Comment by sammosummo** [comment]
Now I feel very silly, that was the problem. Thanks for the quick response.
