### ISSUE TITLE
sounddevice.PortAudioError: Error opening InputStream: Device unavailable [PaErrorCode -9985]

### ISSUE THREAD

**Issue by demongolem** [spatialaudio/python-sounddevice#173]
When trying to record, I use the line

`myrecording = sd.rec(duration * fs, samplerate=fs, channels=2,dtype='float64')`

This leads to 

> Traceback (most recent call last):
  File "sd_test.py", line 7, in <module>
    myrecording = sd.rec(duration * fs, samplerate=fs, channels=2,dtype='float64')
  File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\sounddevice.py", line 224, in rec
    ctx.input_dtype, callback, blocking, **kwargs)
  File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\sounddevice.py", line 2417, in start_stream
    **kwargs)
  File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\sounddevice.py", line 1301, in __init__
    **_remove_self(locals()))
  File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\sounddevice.py", line 780, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\sounddevice.py", line 2572, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Device unavailable [PaErrorCode -9985]

When I do `python -m sounddevice` I get this line:

> >  1 Microphone (Plantronics C320), MME (2 in, 0 out)

Why would this device not be available for recording?

**Comment by demongolem** [comment]
Upon further probing, even though the above line shows the headset microphone as the default and it is in fact the default for the Windows system I am using, the only device that works is

> 17 Jack Mic (Realtek HD Audio Front Mic input), Windows WDM-KS (2 in, 0 out)

If I used the plotline.py example for example which is in the repository and I unplug my headset, I see it run without error and pick up my voice.

Usually, I will have my headset plugged in so I can google hangout people online.  It doesn't seem right that I have to try to find which device number is Jack Mic and then use that overwriting the default input device for my computer which works just fine on hangout.

**Comment by mgeier** [comment]
The error message and the behavior you are describing are directly provided by the underlying PortAudio library. There is nothing I can do in the `sounddevice` module to change that, any changes would have to be done in PortAudio itself.

You should probably ask about this on the PortAudio mailing list: http://portaudio.com/contacts.html

**Comment by mgeier** [comment]
@demongolem Are there any news on this issue?

**Comment by demongolem** [comment]
No, I did report to PortAudio, but there has been no response on that.

**Comment by mgeier** [comment]
OK, thanks for reporting this, could you please provide a link to the issue so we can follow it here?

**Comment by demongolem** [comment]
https://www.assembla.com/spaces/portaudio/tickets/293-portaudio-not-able-to-use-my-default-recording-device

**Comment by mgeier** [comment]
Thanks for the link!

You would probably reach more people (including PortAudio *users*, not only core developers) when you ask on the mailing list.

Probably there is somebody else who could try the Plantronics C320 on Windows/MME?

I guess this is the device: https://www.plantronics.com/us/en/product/blackwire-310-320

And just to make sure: This problem only occurs with this one device, right?
Did you try other external USB devices?

**Comment by rajulanka222** [comment]
Hi,
     I have a similar kind of issue, any solution found? 
I have a simple pyQT from, which displays all the devices, and I select the Device and start streaming, everthing is fine. then I send the stop signal where I closed the stream()... 
when I click the 'Start' then I am getting below error. (I am running this on Linux Mint 19.1) 
once this is done, I am going to test on Windows 10. 
---------------------------------------------------------------
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
Traceback (most recent call last):
  File "/home/raju/PycharmProjects/connectme/src/main/python/main.py", line 210, in connectserver
    stream = sd.RawStream(samplerate=samplerate, channels=channels, dtype='int16', callback=callback)
  File "/home/raju/PycharmProjects/connectme/venv/lib/python3.7/site-packages/sounddevice.py", line 1345, in __init__
    **_remove_self(locals()))
  File "/home/raju/PycharmProjects/connectme/venv/lib/python3.7/site-packages/sounddevice.py", line 861, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/home/raju/PycharmProjects/connectme/venv/lib/python3.7/site-packages/sounddevice.py", line 2653, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Device unavailable [PaErrorCode -9985]

any help is really appreciated. 
--thanks

**Comment by 010Hamza010** [comment]
Did u find a solution or not yet?
Guz i have the same problem

**Comment by Ananthu27** [comment]
i have the same problem too .

**Comment by rkuchkarov** [comment]
I have this problem too

**Comment by mgeier** [comment]
Did you ask on the PortAudio mailing list (http://portaudio.com/contacts.html)?

**Comment by csarami** [comment]
I guess same error. I am also on MacMojave and try to play a sound file if a microphone signal goes above a threshold. I have :

    import sounddevice as sd
    import soundfile as sf
    import numpy as np
    duration = 5  # seconds
    
    
    threshold = 30
    filename = "./data/piano.wav"
    data, fs = sf.read(filename, dtype='float32')  
    
    
    def print_sound(indata, outdata, frames, time, status):
        if status:
            print(status)
        global threshold, data, fs
        volume_norm = 5*np.linalg.norm(indata)
        if volume_norm > threshold: 
            print("so loud!!!!")
            sd.play(data, fs)
    
    with sd.Stream(callback=print_sound):
        sd.sleep(1000*duration)

When I run this the sound goes above the threshold, however, it cannot open the output Stream as follows;


    $python3 main.py 
    input underflow
    input underflow
    input underflow
    so loud!!!!
    so loud!!!!
    input overflow, output underflow
    so loud!!!!
    input overflow, output underflow
    so loud!!!!
    ||PaMacCore (AUHAL)|| Error on line 1316: err=''nope'', msg=Audio Hardware: Illegal Operation
    From cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x10caf8680>:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sounddevice.py", line 881, in callback_ptr
        callback, idata, odata, frames, time, status)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sounddevice.py", line 2678, in _wrap_callback
        callback(*args)
      File "main.py", line 17, in print_sound
        sd.play(data, fs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sounddevice.py", line 177, in play
        **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sounddevice.py", line 2578, in start_stream
        **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sounddevice.py", line 1489, in __init__
        **_remove_self(locals()))
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sounddevice.py", line 895, in __init__
        'Error opening {}'.format(self.__class__.__name__))
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sounddevice.py", line 2738, in _check
        raise PortAudioError(errormsg, err)
    sounddevice.PortAudioError: Error opening OutputStream: Internal PortAudio error [PaErrorCode -9986]

I have restarted my iMac ( Mojave) and still get the same error. 

Any help would be much appreciated.

CS

**Comment by otori334** [comment]
I guess same error too. macOS Big Sur 11.5 beta, sounddevice 0.4.1.
```
# Used to convert waveform data into a 2-byte numeric sequence
import wave as wave
import numpy as np
import sounddevice as sd

#Sample files
sample_wave_file="./CMU_ARCTIC/cmu_us_aew_arctic/wav/arctic_a0001.wav"

#Load a file
wav=wave.open(sample_wave_file)

#Reads waveform data in PCM format
data=wav.readframes(wav.getnframes())

#Convert data to a 2-byte numeric string
data=np.frombuffer(data, dtype=np.int16)

#Playback data
sd.play(data,wav.getframerate())

status = sd.wait()
```
When I run this;
```
(.env) otori334@OTRMBP SSS % python3 /Users/otori334/GitHub/SSS/playback.py            
||PaMacCore (AUHAL)|| Error on line 1316: err='-66748', msg=Unknown Error
Traceback (most recent call last):
  File "/Users/otori334/GitHub/SSS/playback.py", line 20, in <module>
    sd.play(data,wav.getframerate())
  File "/Users/otori334/GitHub/SSS/.env/lib/python3.9/site-packages/sounddevice.py", line 174, in play
    ctx.start_stream(OutputStream, samplerate, ctx.output_channels,
  File "/Users/otori334/GitHub/SSS/.env/lib/python3.9/site-packages/sounddevice.py", line 2573, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
  File "/Users/otori334/GitHub/SSS/.env/lib/python3.9/site-packages/sounddevice.py", line 1488, in __init__
    _StreamBase.__init__(self, kind='output', wrap_callback='array',
  File "/Users/otori334/GitHub/SSS/.env/lib/python3.9/site-packages/sounddevice.py", line 892, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/Users/otori334/GitHub/SSS/.env/lib/python3.9/site-packages/sounddevice.py", line 2738, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening OutputStream: Internal PortAudio error [PaErrorCode -9986]
```

**Comment by otori334** [comment]
My problem was solved with this method #299

>brew install portaudio --HEAD

Thanks

**Comment by staniko** [comment]
stream.start() did the magic for me, before involing stream.read().

**Comment by warrenarea** [comment]
> sounddevice.PortAudioError: Error opening RawStream: Unanticipated host error [PaErrorCode -9999]: 'Undefined external error.' [MME error 1]

I resolved this by enabling `"Let apps access your microphone"` in Windows 10/11.
a setting in `System > Privacy & Security > Microphone`

**Comment by joachimpoutaraud** [comment]
Uninstalling sounddevice from `pip` and reinstalling using `conda` worked for me
``` 
pip uninstall sounddevice
conda install -c conda-forge python-sounddevice
```

**Comment by wnorthrup** [comment]
> Uninstalling sounddevice from `pip` and reinstalling using `conda` worked for me
> 
> ```
> pip uninstall sounddevice
> conda install -c conda-forge python-sounddevice
> ```

This worked for me. Thanks.

**Comment by Sudam-Praveen** [comment]
Exception in thread Thread-2 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\sudam\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\sudam\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sudam\Demo\pythonProject\voice_to_text.py", line 78, in <lambda>
    threading.Thread(target=lambda: record_audio(file_to_write, status_label, countdown_text)).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sudam\Demo\pythonProject\voice_to_text.py", line 37, in record_audio
    audio_recording = sd.rec(duration * SAMPLE_RATE, samplerate=SAMPLE_RATE, channels=1, dtype='int16',device=1)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sudam\Demo\pythonProject\.venv\Lib\site-packages\sounddevice.py", line 279, in rec
    ctx.start_stream(InputStream, samplerate, ctx.input_channels,
  File "C:\Users\sudam\Demo\pythonProject\.venv\Lib\site-packages\sounddevice.py", line 2626, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sudam\Demo\pythonProject\.venv\Lib\site-packages\sounddevice.py", line 1440, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "C:\Users\sudam\Demo\pythonProject\.venv\Lib\site-packages\sounddevice.py", line 909, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "C:\Users\sudam\Demo\pythonProject\.venv\Lib\site-packages\sounddevice.py", line 2794, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error opening InputStream: Unanticipated host error [PaErrorCode -9999]: 'An invalid parameter was passed to a system function.' [MME error 11]

I have also got this error what should i do?
