### ISSUE TITLE
feature request: support setting PaWasapiStreamCategory

### ISSUE THREAD

**Issue by YZhao33** [spatialaudio/python-sounddevice#220]
Is it possible to support setting PaWasapiStreamCategory in Windows. We try to capture procesed speech signal (enhanced or beamformed) from the microphone, other than raw audio. 
The audio stream is created by PortAudio by default as “eAudioCategoryOther”. This will record raw audio. If the stream is created as “eAudioCategorySpeech”, processed audio will be recorded. I have verified this using C code calling WASAPI. However, SoundDevice doesn’t provide an API to set audio stream category. I tried to modify SoundDevice code to create a “speech” audio stream. That doesn’t work either. 
Any idea to work around it for the time being? And will you support it in later time?

**Comment by mgeier** [comment]
> Is it possible to support setting PaWasapiStreamCategory in Windows.

I think so.

It's on the list of not-yet-implemented platform-specific features: https://github.com/spatialaudio/python-sounddevice/issues/4#issuecomment-298019776.

It should be straightforward to implement this feature in the `WasapiSettings` class.
We would just need a new keyword argument (e.g. `stream_category`?) which allows specifying the options listed in http://portaudio.com/docs/v19-doxydocs-dev/pa__win__wasapi_8h.html#ad97a45cc69a868e307e1111e715e6d20.

Would case-insensitive strings make sense for those values?
E.g. `stream_category='speech'`?

> Any idea to work around it for the time being?

Probably this works (untested!):

```python
import sounddevice as sd
duration = ...
fs = ...
wasapi_settings = sd.WasapiSettings()
wasapi_settings._streaminfo.streamCategory = sd._lib.eAudioCategorySpeech
my_rec = sd.rec(int(duration * fs), samplerate=fs, channels=1, extra_settings=wasapi_settings)
```

> And will you support it in later time?

Why not?
Would you like to make a PR for this?

**Comment by YZhao33** [comment]
Thank you for reply!
The workaround doesn’t work. It looks like portaudio doesn’t support it yet. Here is the error message:
Traceback (most recent call last):
  File "test2.py", line 9, in <module>
    myrecording = sd.rec(int(seconds * fs), samplerate=fs, channels=1, extra_settings=wasapi_settings)
  File "C:\Users\wcaltest\Anaconda3\lib\site-packages\sounddevice.py", line 280, in rec
    ctx.input_dtype, callback, blocking, **kwargs)
  File "C:\Users\wcaltest\Anaconda3\lib\site-packages\sounddevice.py", line 2498, in start_stream
    **kwargs)
  File "C:\Users\wcaltest\Anaconda3\lib\site-packages\sounddevice.py", line 1382, in __init__
    **_remove_self(locals()))
  File "C:\Users\wcaltest\Anaconda3\lib\site-packages\sounddevice.py", line 861, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "C:\Users\wcaltest\Anaconda3\lib\site-packages\sounddevice.py", line 2653, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Incompatible host API specific stream info [PaErrorCode -9984]

Is there a way to fix this in portAudio?

**Comment by mgeier** [comment]
I think you might not have selected the correct device (one that's actually a WASAPI device)?

I forgot to add this to my example above:

```python
device = # select some WASAPI device
...
my_rec = sd.rec(int(duration * fs), device=device, samplerate=fs, channels=1, extra_settings=wasapi_settings)
```

**Comment by YZhao33** [comment]
Here is the queried devices on Windows. There is no WASAPI devices. Are there any packages needed to be installed and initialized? 
```
>>> sd.query_devices()
  0 Microsoft Sound Mapper - Input, MME (2 in, 0 out)
> 1 Microphone Array (Realtek USB2., MME (2 in, 0 out)
  2 Microphone Array (Realtek High , MME (2 in, 0 out)
  3 Microsoft Sound Mapper - Output, MME (0 in, 2 out)
< 4 Speakers (Realtek High Definiti, MME (0 in, 2 out)
```

**Comment by mgeier** [comment]
I don't really know, I'm not a Windows user.
Probably someone else who is reading this can help us out?

You probably need a certain Windows version for WASAPI?

Are you using the PortAudio DLL that's packaged with the `sounddevice` Pip package?
This DLL should support WASAPI, but if you use a different DLL it might be disabled.

You can check which DLL you are using with:

```python
import sounddevice as sd
print(sd._libname)
```

To find out whether your system supports WASAPI, you could also try a different application (that uses PortAudio), e.g. Audacity (and check whether WASAPI is available in the settings).

**Comment by mgeier** [comment]
@YZhao33 Any news on this?
