### ISSUE TITLE
ounddevice.PortAudioError: Error starting stream: Unanticipated host error [PaErrorCode -9999]

### ISSUE THREAD

**Issue by mocher72** [spatialaudio/python-sounddevice#231]
Problem when using a callback

When I call the  sd.play(data, fs, device = 16, blocksize=80) inline or outside of a loop it plays the sound back OK.  This is on a WASAPI device.

When I try to trigger this in a listener loop for keypress I get the following error

Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\Sean\Anaconda3\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\Sean\Anaconda3\lib\site-packages\pynput\keyboard\_win32.py", line 280, in _process
    self.on_press(key)
  File "C:\Users\Sean\Anaconda3\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "C:\Users\Sean\Documents\Keyboard Development\Software\Python\vibrate_effect.py", line 33, in on_press
    sd.play(data, fs, device = 16, blocksize=80)
  File "C:\Users\Sean\Anaconda3\lib\site-packages\sounddevice.py", line 165, in play
    **kwargs)
  File "C:\Users\Sean\Anaconda3\lib\site-packages\sounddevice.py", line 2482, in start_stream
    self.stream.start()
  File "C:\Users\Sean\Anaconda3\lib\site-packages\sounddevice.py", line 1056, in start
    _check(err, 'Error starting stream')
  File "C:\Users\Sean\Anaconda3\lib\site-packages\sounddevice.py", line 2634, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error starting stream: Unanticipated host error [PaErrorCode -9999]: 'AUDCLNT_E_UNSUPPORTED_FORMAT' [Windows WASAPI error -2004287480]
alphanumeric key f pressed
Traceback (most recent call last):

  File "C:\Users\Sean\Documents\Keyboard Development\Software\Python\vibrate_effect.py", line 48, in <module>
    listener.join()

  File "C:\Users\Sean\Anaconda3\lib\site-packages\pynput\_util\__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)

  File "C:\Users\Sean\Anaconda3\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)

  File "C:\Users\Sean\Anaconda3\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)

  File "C:\Users\Sean\Anaconda3\lib\site-packages\pynput\keyboard\_win32.py", line 280, in _process
    self.on_press(key)

  File "C:\Users\Sean\Anaconda3\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:

  File "C:\Users\Sean\Documents\Keyboard Development\Software\Python\vibrate_effect.py", line 33, in on_press
    sd.play(data, fs, device = 16, blocksize=80)

  File "C:\Users\Sean\Anaconda3\lib\site-packages\sounddevice.py", line 165, in play
    **kwargs)

  File "C:\Users\Sean\Anaconda3\lib\site-packages\sounddevice.py", line 2482, in start_stream
    self.stream.start()

  File "C:\Users\Sean\Anaconda3\lib\site-packages\sounddevice.py", line 1056, in start
    _check(err, 'Error starting stream')

  File "C:\Users\Sean\Anaconda3\lib\site-packages\sounddevice.py", line 2634, in _check
    raise PortAudioError(errormsg, err, hosterror_info)

PortAudioError: Error starting stream: Unanticipated host error [PaErrorCode -9999]: 'AUDCLNT_E_UNSUPPORTED_FORMAT' [Windows WASAPI error -2004287480]

This does not occur when using MME but the delay is unacceptable so I want to use WASAPI.

Code to replicate is attached and pasted below
[vibrate_effect.zip](https://github.com/spatialaudio/python-sounddevice/files/4417877/vibrate_effect.zip)

# -*- coding: utf-8 -*-
"""
Created on Mon Mar 30 15:18:28 2020

@author: Sean
"""

import soundfile as sf
import os
from pynput import keyboard
import numpy as np
import sounddevice as sd

fs = 8000

#create a sin wave
print(sd.query_devices())

amplitude = 1 #amplitude of the wave
freq = 100 # frequency of the wave Hz
length = 0.1 # length of the wave in seconds

time = np.arange(0, length, 1/fs)

data = amplitude * np.sin(2 * np.pi * freq * time)

def on_press(key):
    try:
        print('alphanumeric key {0} pressed'.format(key.char))
        sd.stop()
        sd.play(data, fs, device = 16, blocksize=80)
            
    except AttributeError:
        print('special key {0} pressed'.format(key))

def on_release(key):
    print('{0} released'.format(key))
    if key == keyboard.Key.esc:
        # Stop listener
        return False
    
# Collect events until released
with keyboard.Listener(
       on_press=on_press,
       on_release=on_release) as listener:
    listener.join()

***********************************************************************************************
Soundcard query

0  - Input, MME (2 in, 0 out)
>  1 Discrete4 Recording (Discrete4), MME (16 in, 0 out)
   2  - Output, MME (0 in, 2 out)
<  3 Realtek Digital Output(Optical), MME (0 in, 2 out)
   4 Speakers (Cypress Digital Audio, MME (0 in, 2 out)
   5 Discrete4 Playback (Discrete4), MME (0 in, 16 out)
   6 Realtek Digital Output (2- Real, MME (0 in, 2 out)
   7 Primary Sound Capture Driver, Windows DirectSound (2 in, 0 out)
   8 Discrete4 Recording (Discrete4), Windows DirectSound (16 in, 0 out)
   9 Primary Sound Driver, Windows DirectSound (0 in, 2 out)
  10 Realtek Digital Output(Optical) (2- Realtek High Definition Audio), Windows DirectSound (0 in, 2 out)
  11 Speakers (Cypress Digital Audio), Windows DirectSound (0 in, 2 out)
  12 Discrete4 Playback (Discrete4), Windows DirectSound (0 in, 16 out)
  13 Realtek Digital Output (2- Realtek High Definition Audio), Windows DirectSound (0 in, 2 out)
  14 ASIO4ALL v2, ASIO (2 in, 8 out)
  15 Discrete4 ASIO Driver, ASIO (16 in, 16 out)
  16 Speakers (Cypress Digital Audio), Windows WASAPI (0 in, 2 out)
  17 Discrete4 Playback (Discrete4), Windows WASAPI (0 in, 2 out)
  18 Realtek Digital Output (2- Realtek High Definition Audio), Windows WASAPI (0 in, 2 out)
  19 Realtek Digital Output(Optical) (2- Realtek High Definition Audio), Windows WASAPI (0 in, 2 out)
  20 Discrete4 Recording (Discrete4), Windows WASAPI (16 in, 0 out)
  21 Speakers (Realtek HD Audio output), Windows WDM-KS (0 in, 8 out)
  22 Microphone (Realtek HD Audio Mic input), Windows WDM-KS (2 in, 0 out)
  23 Line In (Realtek HD Audio Line input), Windows WDM-KS (2 in, 0 out)
  24 SPDIF Out (Realtek HDA SPDIF Out), Windows WDM-KS (0 in, 2 out)
  25 SPDIF Out (Realtek HDA SPDIF Optical Out), Windows WDM-KS (0 in, 2 out)
  26 Stereo Mix (Realtek HD Audio Stereo input), Windows WDM-KS (2 in, 0 out)
  27 Speaker (Cypress Digital Audio), Windows WDM-KS (0 in, 2 out)
  28 Discrete4 Recording (Discrete4 Recording), Windows WDM-KS (16 in, 0 out)
  29 Discrete4 Playback (Discrete4 Playback), Windows WDM-KS (0 in, 16 out)

**Comment by mgeier** [comment]
Can you please edit your question and add formatting for source code and error messages?

If you need help, see: https://help.github.com/en/github/writing-on-github/about-writing-and-formatting-on-github

**Comment by mocher72** [comment]
I have updated the issue, hopefully easier to read now, sorry first time posting so I didn't know the formatting :)

**Comment by mgeier** [comment]
Thanks. Please format the program output also like code (i.e. with triple backticks).

**Comment by mgeier** [comment]
Thanks, now it's readable!

The error mentions `AUDCLNT_E_UNSUPPORTED_FORMAT`, which seems to be documented e.g. here: https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-isformatsupported

Did you try a different sampling rate?

You should be able to check like this if some settings are supported:

```python
sd.check_output_settings(device=16, samplerate=8000, channels=1) 
```

This will return nothing if the settings are supported and it will raise an exception if not.

**Comment by mgeier** [comment]
> This does not occur when using MME but the delay is unacceptable so I want to use WASAPI.

Just out of curiosity: How does it work with WDM-KS?

**Comment by SoulProficiency** [comment]
`11111`
