### ISSUE TITLE
Unable to play 16khz clip through play_longfile example

### ISSUE THREAD

**Issue by tejas1502** [spatialaudio/python-sounddevice#236]
Hello,

I have a RME soundcard connected to my laptop which supports 44.1khz,48khz and 96khz.
If I play a 48khz clip, it plays fine.
Here, I am trying to play a 16khz clip using play_longfile example under sounddevice.

With this, I get an "queue full" error.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\tom\SoundCardPlayRec.py", line 223, in playLongFile
    q.put(data, timeout=timeout)
  File "C:\Users\tom\AppData\Local\Programs\Python\Python37\lib\queue.py", line 147, in put
    raise Full
queue.Full

I have been trying to debug this issue. 
So, to avoid this error, I am trying to resample audio using librosa, but since my data is in form of buffer object, I converted it to numpy. Even with this, I am getting some other unexpected errors.

Can someone please help with this?

**Comment by tejas1502** [comment]
I have some update on the issue: I have been able to narrow down the issue to silence playback. I see that through, sounddevice it is not able to play silence data. Any suggestions on how i can make sure silence can be played?

**Comment by mgeier** [comment]
Please edit your question according to https://github.com/spatialaudio/python-sounddevice/blob/master/CONTRIBUTING.rst#reporting-problems.
