### ISSUE TITLE
sd.rec returning white noise with 10**38 amplitude on macOS Big Sur.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [spatialaudio/python-sounddevice#317]
On macOS this code is producing a mixture of NaN, all-zero and ~10**38 amplitude waves:

```python
import sounddevice as sd

sample_rate = 44100
duration = 1
audio = sd.rec(duration * sample_rate, samplerate=sample_rate, channels=1)
print(f"{np.mean(audio)=}, {np.std(audio)=}, {np.min(audio)=}, {np.max(audio)=}")
```

```python
# Example outputs
np.mean(audio)=nan, np.std(audio)=nan, np.min(audio)=nan, np.max(audio)=nan
np.mean(audio)=nan, np.std(audio)=nan, np.min(audio)=-3.2219445e+38, np.max(audio)=3.2167317e+38
np.mean(audio)=0.0, np.std(audio)=0.0, np.min(audio)=0.0, np.max(audio)=0.0
```

![image](https://user-images.githubusercontent.com/40036383/109435512-aba76e80-79cf-11eb-8496-0a60e6d09346.png)

When I try to use two channels I also get the following PortAudio error:

```
Traceback (most recent call last):
  File "sound.py", line 6, in <module>
    audio = sd.rec(duration * sample_rate, samplerate=sample_rate, channels=2)
  File ".venv/lib/python3.8/site-packages/sounddevice.py", line 274, in rec
    ctx.start_stream(InputStream, samplerate, ctx.input_channels,
  File ".venv/lib/python3.8/site-packages/sounddevice.py", line 2573, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
  File ".venv/lib/python3.8/site-packages/sounddevice.py", line 1415, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File ".venv/lib/python3.8/site-packages/sounddevice.py", line 892, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File ".venv/lib/python3.8/site-packages/sounddevice.py", line 2738, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Invalid number of channels [PaErrorCode -9998]
```

I tried installing PyAudio to check if that behaved similarly, however the pip install fails after 20 errors like this:

```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/os/workgroup_interval.h:123:30: error: unknown type name 'os_workgroup_interval_t'
```

So, maybe there's a Big Sur incompatibility that `sounddevice` isn't detecting? I'm not at all familiar with this part of the stack.

**Comment by mgeier** [comment]
This is quite bad, but I don't know what I could do about it on the Python side.

What happens if you select a different `dtype`?

What happens if you use other software that uses PortAudio, e.g. Audacity?

**Comment by phoenix-meadowlark** [comment]
I downgraded to python `3.6.10` to use `pyaudio` earlier this week, and that is working as expected.

I installed `sounddevice` in the same `venv` and am observing the same behavior described above. `pyaudio` was 'recording' all zeros when I tried to run it from vscode's terminal, but it works when running from `iterm` (which I was able to give microphone permissions). `sounddevice` behaves the same in both terminal environments.

**Comment by mgeier** [comment]
Thanks for the update!

Both PyAudio and the `sounddevice` module use PortAudio, so I would expect the same behavior ...

Maybe you are using different versions?

What does `sd.get_portaudio_version()` say?

What is the value of `sd._libname`?

Have you installed `portaudio` with `brew`?

You can try to compile the latest version, or you can try to uninstall it, maybe that helps.

If it still doesn't work, there is hope nevertheless, because it looks like a new PortAudio release will happen within the next few weeks!

**Comment by imyxh** [comment]
Try the `blocking=True` argument. Fixed the same problem for me, because I was mistakenly drawing the graph before waiting for the recording to finish.

**Comment by mgeier** [comment]
Thanks @imyxh, I totally overlooked this!

Instead of `blocking=True` one can also use `sd.wait()`.
