### ISSUE TITLE
Sounddevice isnt detecting portaudio on my MacBook | OSError: PortAudio library not found |

### ISSUE THREAD

**Issue by fvviz** [spatialaudio/python-sounddevice#363]
When i run this code 
```py
import sounddevice
```
 i get this error
```py
Traceback (most recent call last):
  File "/Users/faizrahim/PycharmProjects/voice-lag-simul/venv/lib/python3.8/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/faizrahim/PycharmProjects/voice-lag-simul/writejson.py", line 1, in <module>
    import sounddevice
  File "/Users/faizrahim/PycharmProjects/voice-lag-simul/venv/lib/python3.8/site-packages/sounddevice.py", line 80, in <module>
    import _sounddevice_data
ModuleNotFoundError: No module named '_sounddevice_data'
```

This is how i installed sounddevice
```
pip3 install sounddevice
```

But I'm sure i installed portaudio on my mac. Even Pyaudio seems to work fine but sounddevice is not working, What can i do now?

**Comment by CatherineHenry** [comment]
I'm seeing the same as OP and am running on an M1 Mac. 

I do have portaudio installed via brew and have tried running 
`pip3 install --no-cache-dir --global-option='build_ext' --global-option='-I/usr/local/opt/portaudio/include' --global-option='-L/usr/local/opt/portaudio/lib' sounddevice` but no success thus far

**Comment by fab-jul** [comment]
I'm still getting the error, on an Intel Macbook w/ 11.4. I tried the `brew install portaudio --HEAD` trick mentioned in various places without luck. My sounddevice version seems to be 0.4.3.

**Comment by fab-jul** [comment]
I never saw any permissions pop up, is there a way to force this? And also, fyi, I'm using Python 3.10

**Comment by fab-jul** [comment]
Update: fixed by downgrading to Python 3.8. Maybe some other issue was present. I did now create a few conda env, and then used pip to install `sounddevice`.
