### ISSUE TITLE
sounddevice.PortAudioError: Error opening Stream: Device unavailable [PaErrorCode -9985]

### ISSUE THREAD

**Issue by Vanshaj712** [spatialaudio/python-sounddevice#390]
sounddevice.PortAudioError: Error opening Stream: Device unavailable [PaErrorCode -9985]
This is my Windows machine with X86 and windows 10

 python client.py
client started
_________________________________________________________________________________
Traceback (most recent call last):
  File "client.py", line 34, in <module>
    sdstream = sd.Stream(samplerate=44100, channels=1, dtype='float32')
  File "C:\Users\milan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sounddevice.py", line 1795, in __init__
    **_remove_self(locals()))
  File "C:\Users\milan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sounddevice.py", line 895, in __init__
    'Error opening {}'.format(self.__class__.__name__))
  File "C:\Users\milan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sounddevice.py", line 2741, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening Stream: Device unavailable [PaErrorCode -9985]

**Comment by mgeier** [comment]
Please have a look at https://python-sounddevice.readthedocs.io/CONTRIBUTING.html#reporting-problems and edit your question accordingly.
