### ISSUE TITLE
Internal PortAudio error [PaErrorCode -9986]

### ISSUE THREAD

**Issue by speeding-rocket** [spatialaudio/python-sounddevice#454]
> I have created the following script:

import sounddevice as sd

sample_rate = 44100 
duration = 2 
recording = sd.rec(int(seconds * sample_rate), samplerate=sample_rate, channels=1)
sd.wait()  

> When running this script, I get the following error message: 
||PaMacCore (AUHAL)|| Error on line 1277: err='-66748', msg=Unknown Error
---------------------------------------------------------------------------
PortAudioError                            Traceback (most recent call last)
Cell In[6], line 7
      4 fs = 44100  # Sample rate
      5 seconds = 3  # Duration of recording
----> 7 myrecording = sd.rec(int(seconds * fs), samplerate=fs, channels=1)
      8 sd.wait()  # Wait until recording is finished
      9 write('output.wav', fs, myrecording)

File /opt/anaconda3/lib/python3.9/site-packages/sounddevice.py:274, in rec(frames, samplerate, channels, dtype, out, mapping, blocking, **kwargs)
    271     ctx.read_indata(indata)
    272     ctx.callback_exit()
--> 274 ctx.start_stream(InputStream, samplerate, ctx.input_channels,
    275                  ctx.input_dtype, callback, blocking, **kwargs)
    276 return out

File /opt/anaconda3/lib/python3.9/site-packages/sounddevice.py:2573, in _CallbackContext.start_stream(self, StreamClass, samplerate, channels, dtype, callback, blocking, **kwargs)
   2570 def start_stream(self, StreamClass, samplerate, channels, dtype, callback,
   2571                  blocking, **kwargs):
   2572     stop()  # Stop previous playback/recording
-> 2573     self.stream = StreamClass(samplerate=samplerate,
   2574                               channels=channels,
   2575                               dtype=dtype,
   2576                               callback=callback,
   2577                               finished_callback=self.finished_callback,
   2578                               **kwargs)
   2579     self.stream.start()
   2580     global _last_callback

File /opt/anaconda3/lib/python3.9/site-packages/sounddevice.py:1415, in InputStream.__init__(self, samplerate, blocksize, device, channels, dtype, latency, extra_settings, callback, finished_callback, clip_off, dither_off, never_drop_input, prime_output_buffers_using_stream_callback)
   1385 def __init__(self, samplerate=None, blocksize=None,
   1386              device=None, channels=None, dtype=None, latency=None,
   1387              extra_settings=None, callback=None, finished_callback=None,
   1388              clip_off=None, dither_off=None, never_drop_input=None,
   1389              prime_output_buffers_using_stream_callback=None):
   1390     """PortAudio input stream (using NumPy).
   1391 
   1392     This has the same methods and attributes as `Stream`, except
   (...)
   1413 
   1414     """
-> 1415     _StreamBase.__init__(self, kind='input', wrap_callback='array',
   1416                          **_remove_self(locals()))

File /opt/anaconda3/lib/python3.9/site-packages/sounddevice.py:892, in _StreamBase.__init__(self, kind, samplerate, blocksize, device, channels, dtype, latency, extra_settings, callback, finished_callback, clip_off, dither_off, never_drop_input, prime_output_buffers_using_stream_callback, userdata, wrap_callback)
    890     userdata = _ffi.NULL
    891 self._ptr = _ffi.new('PaStream**')
--> 892 _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
    893                           samplerate, blocksize, stream_flags,
    894                           callback_ptr, userdata),
    895        'Error opening {}'.format(self.__class__.__name__))
    897 # dereference PaStream** --> PaStream*
    898 self._ptr = self._ptr[0]

File /opt/anaconda3/lib/python3.9/site-packages/sounddevice.py:2738, in _check(err, msg)
   2735     hosterror_info = host_api, info.errorCode, hosterror_text
   2736     raise PortAudioError(errormsg, err, hosterror_info)
-> 2738 raise PortAudioError(errormsg, err)

PortAudioError: Error opening InputStream: Internal PortAudio error [PaErrorCode -9986]

The list of devices is as follows: 

$ python3 -m sounddevice

> 0 MacBook Pro Microphone, Core Audio (1 in, 0 out)
< 1 MacBook Pro Speakers, Core Audio (0 in, 2 out)
  2 Echo360 System Audio, Core Audio (2 in, 2 out)
  3 Microsoft Teams Audio, Core Audio (2 in, 2 out)
  4 ZoomAudioDevice, Core Audio (2 in, 2 out)
  5 Soundflower and Bose, Core Audio (0 in, 0 out)
  6 Soundflower and speakers, Core Audio (0 in, 2 out)
  7 SF and External Headphones, Core Audio (0 in, 0 out)

Could you please advise me on how to solve this problem?

**Comment by PraxTube** [comment]
The code you provided and the code you ran that gave the error are a little different.

```python
import sounddevice as sd

sample_rate = 44100 
duration = 2 
# recording = sd.rec(int(seconds * sample_rate), samplerate=sample_rate, channels=1)
rec = sd.rec(int(sample_rate*duration), samplerate = sample_rate, channels = 1)
sd.wait()
```

Running this code doesn't give me any errors. Perhaps you could try to run one of the [recording examples](https://github.com/spatialaudio/python-sounddevice/tree/master/examples). If you get the same error there as well, then it has to be something about your set up (maybe not all dependencies are installed).

**Comment by speeding-rocket** [comment]
Thank you very much for your feedback. Sorry for the typo in the code, I have copied a source code and error message from two different attempts. However the snippet from your comment still throws the same error. 

I originally wanted to run it with two channels but it came with another error, `PortAudioError: Error opening InputStream: Invalid number of channels [PaErrorCode -9998]`, which however is not surprising given that the default input has only one channel. 

I have tried the recording examples from the link you list, and the same error comes up. 

I have been installing and reinstalling PortAudio and various python audio libraries and their dependencies and I think that it is not my setup that is at fault. I ran an analogous code in pyaudio and I got the exact same error. I started to think that this might be an error on PortAudio side and subsequently raised an issue on their site (PortAudio/portaudio, #771) but so far I have had no answer. 

Meanwhile, I was finally able to record sounds using the `pvrecorder` library. This appears to be a huge commercial resource but they do let users access some basic functionality for free. 

This is however not ideal for me and I would still prefer to use sounddevice library. I would be grateful for any ideas for possible solutions of this hiccup.

**Comment by mgeier** [comment]
How exactly are you running your Python code?
In the terminal?

It might be an issue about microphone permissions.

**Comment by laughingrice** [comment]
I am seeing the same problem on an intel mac (13" 2017 running macos ventura 13.4.1), there seems to be some problem with the anaconda package. The following code fails with error 9986 with the anaconda package but runs fine with the pip pacakge

Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:10:28) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import sounddevice as sd
>>> sd.default.samplerate = 44100
>>> sd.default.channels = 2
>>> myrecording = sd.rec(int(44100*1))

||PaMacCore (AUHAL)|| Error on line 1277: err='-66748', msg=Unknown Error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/micha/opt/miniconda3/envs/sounddevice2/lib/python3.11/site-packages/sounddevice.py", line 276, in rec
    ctx.start_stream(InputStream, samplerate, ctx.input_channels,
  File "/Users/micha/opt/miniconda3/envs/sounddevice2/lib/python3.11/site-packages/sounddevice.py", line 2582, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/micha/opt/miniconda3/envs/sounddevice2/lib/python3.11/site-packages/sounddevice.py", line 1421, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/Users/micha/opt/miniconda3/envs/sounddevice2/lib/python3.11/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/Users/micha/opt/miniconda3/envs/sounddevice2/lib/python3.11/site-packages/sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Internal PortAudio error [PaErrorCode -9986]

**Comment by laughingrice** [comment]
On second test, the problem is actually with the anaconda portaudio package, renaming the portuadio libraries so that the brew version is used makes things work.
