### ISSUE TITLE
Cannot run threaded on a Windows 10 machine

### ISSUE THREAD

**Issue by cfuttrup** [spatialaudio/python-sounddevice#546]
I cannot run threaded on a Windows 10 machine, but works fine on Linux, and it works fine under Windows so long as the playrec is executed non-threaded.
My take is that sounddevice links to the PortAudio .dll file in a way that doesn't facilitate threading (but differently under Linux), possibly just a timing issue, or, maybe it's a PortAudio issue, in which case I think the right way to approach this is that you guys from sounddevice report the issue upstream.

My system:
Lenovo T480, Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz, 16 GB of RAM (6 years old)
USB port 'SuperSpeed' and with charging capability, no issue powering the Focusrite Scarlett 2i2, 3rd Gen, Firmware 1605
Python 3.10.10 and pip 24.2
threading comes with Python (default)
Numpy version 1.26.4
sounddevice 0.4.7

>>> print(sd._libname)
C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\_sounddevice_data\portaudio-binaries\libportaudio64bit.dll
>>> print(sd.get_portaudio_version())
(1246976, 'PortAudio V19.7.0-devel, revision 147dd722548358763a8b649b3e4b41dfffbcfbb6')

I have created a script named `test3.py` which works under both Linux and Windows. I've added a bit of 'luxury' so this should be easy for anyone to test:

```python

import numpy as np
import sounddevice as sd
import threading

SUPPORTED_APIS    = ['ALSA','ASIO']
SUPPORTED_DEVICES = ['Focusrite','Scarlett']

f1   = 4                   # Start frequency (Hz)
f2   = 24000               # End frequency (Hz)
T    = 4                   # Sweep time (seconds)
A    = 3                   # Sweep amplitude (Volt peak)

pvec={                     # Python dictionary (dict) of parameters
    'block':32,            # Used in 'func'
    'dev_index':[0,0],     # Used in 'func'
    'device':'none',       # Name of device
    'hostapi_name':'ALSA',
    'pad':200.0,           # Padding of signal (200 ms)
    'rate':48000           # Sample rate (frequency, 48 kHz)
}

all_devices = sd.query_devices()
all_apis    = sd.query_hostapis()

#------------------------------------
# Scan devices to match keywords in supported devices and apis
def devicescanner():
    for dev in all_devices:
        name = dev['name']
        hostapi = dev['hostapi']
        hostapi_name = all_apis[hostapi]['name']
        for myapi in SUPPORTED_APIS:
            if myapi in hostapi_name:
                for mydev in SUPPORTED_DEVICES:
                    if mydev in name:
                        [dev_index] = [dev['index']]
                        return name, hostapi_name, [dev_index]*2

pvec['device'], pvec['hostapi_name'], pvec['dev_index'] = devicescanner()
print(pvec)                # DEBUG code

#------------------------------------
# Calculate some variables

n = int(pvec['rate']*T)    # number of samples
tau = np.linspace(0,1,n,endpoint=False)
t = tau*T                  # sweep vector (t) in seconds

# Exponential sine ('Farina') sweep
w1 = 2*np.pi*f1            # Start frequency (rad/s)
k = np.log(f2/f1)/T        # Sweep rate
phi = w1/k*(np.exp(k*t)-1) # Phase vector
x = A*np.sin(phi)          # Stimulus signal

npad = int(pvec['rate']*pvec['pad']/1000.0)

# Zero buffer
x0 = np.zeros([npad])
# Prepend zeros to signal
xp = np.append(x0,x)
xp = np.append(xp,x0)      # xp = Stimulus with padding

#------------------------------------
if pvec['hostapi_name']=='ASIO':
    print('Using ASIO')    # DEBUG code
#    asio_in = sd.AsioSettings(channel_selectors=pvec['dev_index'])
#    asio_out = sd.AsioSettings(channel_selectors=pvec['dev_index'])
#    sd.default.extra_settings = asio_in, asio_out

# Real signal
def func(pvec,rval):
    yvec = sd.playrec(xp,
                  device=pvec['dev_index'],
                  channels=2,
                  samplerate=pvec['rate'],
                  blocksize=pvec['block'])
    sd.wait()
    rval['y'] = yvec

rval = {}                  # RETURN values (initialize)
func(pvec,rval)
if rval != {}:
    print("Success!")
    rval1 = rval           # store - this works ...

rval = {}                  # RETURN values (initialize, again)
# Try running 'func' in a thread - NOT WORKING under MS Windows ...
# Compute sweep using new thread (not main thread)
pthread = threading.Thread(target=func,args=[pvec,rval])
pthread.start()
# Rejoin main thread here
pthread.join()
```

Under Linux the script chooses ALSA. Under Windows the script chooses ASIO.
Running my script on a Windows Windows 10 Pro (64 bit), 22H2, 2024-04-01 machine, I got this error:

```
D:\Userdata\Claus\Documents\Gits\sweep\tests>python test3.py
{'block': 32, 'dev_index': [12, 12], 'device': 'Focusrite USB ASIO', 'hostapi_name': 'ASIO', 'pad': 200.0, 'rate': 48000}
Using ASIO
Success!
Exception in thread Thread-1 (func):
Traceback (most recent call last):
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Userdata\Claus\Documents\Gits\sweep\tests\test3.py", line 72, in func
    yvec = sd.playrec(xp,
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 369, in playrec
    ctx.start_stream(Stream, samplerate,
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 2605, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 1808, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 906, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 2768, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error opening Stream: Unanticipated host error [PaErrorCode -9999]: 'Failed to load ASIO driver' [ASIO error 0]

D:\Userdata\Claus\Documents\Gits\sweep\tests>
```

From above, you see the 'Success!' output, so everything works, if not threaded.
From above error, I conclude there might be an issue with PortAudio and Python threading (only under Windows).
In Windows the code prints dev_index = [12, 12] and 'Using ASIO' and this is the correct channels on my machine (see listing below).

```
D:\sweep\tests>python -m sounddevice
   0 Microsoft Sound Mapper - Input, MME (2 in, 0 out)
>  1 Microphone Array (Realtek(R) Au, MME (2 in, 0 out)
   2 Analogue 1 + 2 (Focusrite USB A, MME (2 in, 0 out)
   3 Microsoft Sound Mapper - Output, MME (0 in, 2 out)
<  4 Speakers (Focusrite USB Audio), MME (0 in, 2 out)
   5 Speaker/HP (Realtek(R) Audio), MME (0 in, 2 out)
   6 Primary Sound Capture Driver, Windows DirectSound (2 in, 0 out)
   7 Microphone Array (Realtek(R) Audio), Windows DirectSound (2 in, 0 out)
   8 Analogue 1 + 2 (Focusrite USB Audio), Windows DirectSound (2 in, 0 out)
   9 Primary Sound Driver, Windows DirectSound (0 in, 2 out)
  10 Speakers (Focusrite USB Audio), Windows DirectSound (0 in, 2 out)
  11 Speaker/HP (Realtek(R) Audio), Windows DirectSound (0 in, 2 out)
  12 Focusrite USB ASIO, ASIO (2 in, 2 out)
  13 Speakers (Focusrite USB Audio), Windows WASAPI (0 in, 2 out)
  14 Speaker/HP (Realtek(R) Audio), Windows WASAPI (0 in, 2 out)
  15 Analogue 1 + 2 (Focusrite USB Audio), Windows WASAPI (2 in, 0 out)
  16 Microphone Array (Realtek(R) Audio), Windows WASAPI (2 in, 0 out)
  17 Speakers (Realtek HD Audio output), Windows WDM-KS (0 in, 2 out)
  18 Microphone Array (Realtek HD Audio Mic input), Windows WDM-KS (2 in, 0 out)
  19 Analogue 1 + 2 (wc4800_8210), Windows WDM-KS (2 in, 0 out)
  20 Speakers (wr4800_8210), Windows WDM-KS (0 in, 2 out)
  21 Room Speaker (), Windows WDM-KS (0 in, 2 out)
  22 Headset Earphone (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free AG Audio%0
;(Westend XFi)), Windows WDM-KS (0 in, 1 out)
  23 Headset Microphone (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free AG Audio%0
;(Westend XFi)), Windows WDM-KS (1 in, 0 out)

D:\sweep\tests>
```

By the way, if I set the ASIO channel_selectors (as commented out in the code above), I get a different error:

```
D:\sweep\tests>python test3.py
{'block': 32, 'dev_index': [12, 12], 'device': 'Focusrite USB ASIO', 'hostapi_name': 'ASIO', 'pad': 200.0, 'rate': 48000}
Using ASIO
Traceback (most recent call last):
  File "D:\Userdata\Claus\Documents\Gits\sweep\tests\test3.py", line 81, in <module>
    func(pvec,rval)
  File "D:\Userdata\Claus\Documents\Gits\sweep\tests\test3.py", line 72, in func
    yvec = sd.playrec(xp,
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 369, in playrec
    ctx.start_stream(Stream, samplerate,
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 2605, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 1808, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 906, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "C:\Users\cfutt\AppData\Local\Programs\Python\Python310\lib\site-packages\sounddevice.py", line 2770, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening Stream: Invalid number of channels [PaErrorCode -9998]

D:\sweep\tests>
```

Not sure what I am doing wrong here.

**Comment by mgeier** [comment]
Starting streams on different threads has been reported to be problematic, e.g. #118, #366, #442. Search for "thread" in the issues to find more.

I normally recommend (e.g. https://github.com/spatialaudio/python-sounddevice/issues/442#issuecomment-1312764742) starting the stream from the main thread and communicating between other threads and the callback function if needed.

> My take is that sounddevice links to the PortAudio .dll file in a way that doesn't facilitate threading (but differently under Linux), possibly just a timing issue, or, maybe it's a PortAudio issue

Maybe. Feel free to investigate further!

> By the way, if I set the ASIO channel_selectors (as commented out in the code above), I get a different error

Is this related to the threading problem?

If not, can you please create a separate issue?

**Comment by cfuttrup** [comment]
We have found that running 'multiprocessing' instead has helped. Let me investigate if the ASIO channel_selectors issue is fixed with our changes, or not (and create a separate thread).

**Comment by cfuttrup** [comment]
Apologies for adding a comment to an otherwise closed thread. This comment is related to the question unrelated to the subject, the one about channel_selectors. Answer: The channel selectors are not related to the device index. For example, if the device indices are [12, 12], the channel selectors could be [1]. My confusion might be caused by the example in the sounddevice documentation, where the examples show some high numbers, like asio_out = [12, 13] and asio_in = [8], which mislead me to thinking the channel selectors were related to the device index. They are not, and my Focusrite Scarlett 2i2 has only two channels in and out, hence specifying a high number for the channel_selectors attempts to address a channel that doesn't exist on my device. I hope this clarifies something.
