### ISSUE TITLE
No device detected on Linux

### ISSUE THREAD

**Issue by thomas-haslwanter** [spatialaudio/python-sounddevice#74]
On my Linux system, sounddevice does not detect any devices:

```
import sounddevice as sd
sd.query_devices()
```
produces an empty output.

My setup:
Python: 3.6.0
Name: sounddevice  Version: 0.3.7
Name: cffi                  Version: 1.9.1
Name: PortAudio       Version: 19 (installed with anaconda)

**Comment by mgeier** [comment]
That's strange ...

Can you please try if another application that uses PortAudio (e.g. Audacity) shows any devices?

Can you please provide the output of `sd.get_portaudio_version()`?

You could try to uninstall PortAudio with `conda` and re-install it with you Linux package manager. The package might be called `libportaudio2`.

**Comment by thomas-haslwanter** [comment]
In Audacity, I see all kinds of input devices/channels.

```
In [4]: sd.get_portaudio_version()
Out[4]: (1899, 'PortAudio V19-devel (built Jan 30 2013 00:48:29)')
In [5]: sd.query_devices()
Out[5]:

```
After

`conda uninstall PortAudio`

When I have installed only the "libportaudio2" package, and try
`import sounddevice as sd`
I get the error message below.
(This is also why I installed "PortAudio 19" with conda.)


Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 12:22:00)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sounddevice as sd
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/home/thomas/anaconda3/lib/python3.6/site-packages/cffi/api.py in _load_backend_lib(backend, name, flags)
    756         if '.' not in name and '/' not in name:
--> 757             raise OSError("library not found: %r" % (name,))
    758         return backend.load_library(name, flags)

OSError: library not found: 'portaudio'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-1-3779f1816100> in <module>()
----> 1 import sounddevice as sd

/home/thomas/anaconda3/lib/python3.6/site-packages/sounddevice.py in <module>()
    314
    315 try:
--> 316     _lib = _ffi.dlopen('portaudio')
    317 except OSError:
    318     if _platform.system() == 'Darwin':

/home/thomas/anaconda3/lib/python3.6/site-packages/cffi/api.py in dlopen(self, name, flags)
    137         assert isinstance(name, basestring) or name is None
    138         with self._lock:
--> 139             lib, function_cache = _make_ffi_library(self, name, flags)
    140             self._function_caches.append(function_cache)
    141             self._libraries.append(lib)

/home/thomas/anaconda3/lib/python3.6/site-packages/cffi/api.py in _make_ffi_library(ffi, libname, flags)
    767     import os
    768     backend = ffi._backend
--> 769     backendlib = _load_backend_lib(backend, libname, flags)
    770     #
    771     def accessor_function(name):

/home/thomas/anaconda3/lib/python3.6/site-packages/cffi/api.py in _load_backend_lib(backend, name, flags)
    762         if path is None:
    763             raise     # propagate the original OSError
--> 764         return backend.load_library(path, flags)
    765
    766 def _make_ffi_library(ffi, libname, flags):

OSError: cannot load library libportaudio.so.2: /home/thomas/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)

**Comment by mgeier** [comment]
Thanks for the update.

I'm wondering why the error message (the last line) is still mentioning "anaconda" ...

Can you please try to locate the file `libportaudio.so` (or `libportaudio.so.2`) on your system (you might have multiple of them) and then run the following (adapting the path as appropriate) and post the output here?

```
$ ldd /usr/lib/x86_64-linux-gnu/libportaudio.so
```

Sometimes when you change some libraries, you have to run this (as `root`):

```
# ldconfig
```

But normally the package manager should take care of that ...

**Comment by mgeier** [comment]
There's a SO question that sounds similar: http://stackoverflow.com/q/42404408/.

**Comment by mgeier** [comment]
@thomas-haslwanter Any news on this?

**Comment by thomas-haslwanter** [comment]
I have updated my packages, and now run
cffi: 1.10.0

And now I cannot even import sounddevice :(

`thomas@SILENTIO ~/Coding/scikit-sound $ python
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sounddevice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thomas/anaconda3/lib/python3.6/site-packages/sounddevice.py", line 316, in <module>
    _lib = _ffi.dlopen('portaudio')
  File "/home/thomas/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 140, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/thomas/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 786, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/thomas/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 782, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library libportaudio.so.2: /home/thomas/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)
>>> 
`

**Comment by mgeier** [comment]
What's the output of `sd.get_portaudio_version()` now?

Did you make sure to uninstall PortAudio with `conda`?

Please do this: https://github.com/spatialaudio/python-sounddevice/issues/74#issuecomment-281186813

**Comment by thomas-haslwanter** [comment]
- First I "conda uninstalled" PortAudio
- Still could not import sounddevice
-  Re-installed PortAudio
- Got

In [1]: import sounddevice as sd
In [2]: sd.get_portaudio_version()
Out[2]: (1899, 'PortAudio V19-devel (built Jan 30 2013 00:48:29)')

and yes, there seem to be 2 "libportaudio" files - but I don't know how to handle that:

`SILENTIO thomas # ldd /usr/lib/x86_64-linux-gnu/libportaudi*
/usr/lib/x86_64-linux-gnu/libportaudio.so.2:
	linux-vdso.so.1 =>  (0x00007fff2415f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f80546b8000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f80543b8000)
	libjack.so.0 => /usr/lib/x86_64-linux-gnu/libjack.so.0 (0x00007f805416e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8053e65000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8053c48000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f805387e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f805367a000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e178d42000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f80532f8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f80530e1000)
/usr/lib/x86_64-linux-gnu/libportaudio.so.2.0.0:
	linux-vdso.so.1 =>  (0x00007fffb819f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8f2090e000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f8f2060e000)
	libjack.so.0 => /usr/lib/x86_64-linux-gnu/libjack.so.0 (0x00007f8f203c4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8f200bb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8f1fe9e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8f1fad4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8f1f8d0000)
	/lib64/ld-linux-x86-64.so.2 (0x0000557bf15ec000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8f1f54e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8f1f337000)
SILENTIO thomas # 
`

**Comment by mgeier** [comment]
That's still not the newest PortAudio, but I guess that's not the problem.

The two files are only one file and the other is a symbolic link, at least on my system:

```
$ file /usr/lib/x86_64-linux-gnu/libportaudio.so.2
/usr/lib/x86_64-linux-gnu/libportaudio.so.2: symbolic link to libportaudio.so.2.0.0
```

Probably the problem is `/home/thomas/anaconda3/bin/../lib/libstdc++.so.6`, in other words `/home/thomas/anaconda3/lib/libstdc++.so.6`.
Can you try to (temporarily) remove or rename this file?
I guess the file from Anaconda is old/broken/whatever and shouldn't be involved, you should use the one installed by your package manager, probably this one: `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`?

**Comment by danigamba** [comment]
I'm having the same issue, i can import sounddevice in my conda environment but it doesn't list any device. 

`>>> sd.get_portaudio_version()
(1899, 'PortAudio V19-devel (built Aug 11 2015 07:04:31)')
`
I have also moved libstdc++.so.6 but anything changed.
I'm running on KDE Neon (Ubuntu 16.04 LTS)

**Comment by mgeier** [comment]
@danigamba Did you try what @fluowhy did in #89?

I think this is an Anaconda issue: https://github.com/ContinuumIO/anaconda-issues/issues/2999

**Comment by danigamba** [comment]
Sorry I missed a step!
Solved moving anaconda libstdc++.so.6, copying the system one and reinstalling sounddevice!
Thanks!

**Comment by mgeier** [comment]
@danigamba Good to hear that it works now! I hope this problem will be fixed properly by the Anaconda people ...

**Comment by Chum4k3r** [comment]
Well, i've got the same problem, my pyaudio won't find any device, but my libstdc++.so.6 is now just a symbolic link to two different files in the two directories. At /usr/lib/ is a symb-link to libstdc++.so.6.0.21 and at anaconda3/lib/ is to libstdc++.so.6.0.24... also, the file at /usr/lib/ has 1.6MiB data, and the one at anaconda3 has 8.2MiB...

I tried swapping them, changing names, reinstalling pyaudio and portaudio and everything else there is on SO, github, and a few other linux and python forums, but nothing got it working... I need some light on what to do.

I'm on a Linux Mint 18.3 + Xfce, 64bits, running Anaconda 5.2 with Python 3.6.5, Spyder 3.2, pyaudio 0.2.11, portaudio19. i've got ALSA and PulseAudio updated and working with my built-in soundcard.

At last, but not least, when I uninstalled anaconda and run pyaudio directly on python through terminal, it recognized the sound devices. Well, that's it. Please, any direction will be helpful

**Comment by mgeier** [comment]
@Chum4k3r 

> my pyaudio won't find any device

I'm not able to provide support for PyAudio, you should ask for that at the appropriate channels.

You could try to use the `sounddevice` module, though ... questions about that would be on-topic here.

**Comment by Chum4k3r** [comment]
Well, I'm not using Linux anymore but I've found out something that solved my sounddevice + pyaudio problem with portaudio.

Turns out that PortAudio must be OS installed, while sounddevice and/or pyaudio can be inside the anaconda environment.

I've run

>>> conda uninstall portaudio
>>> sudo apt-get install PortAudio19-dev
>>> pip install sounddevice

Then the sounddevice.query_devices() run properly.

Hope it helps someone

**Comment by mgeier** [comment]
Thanks for the update @Chum4k3r!

FYI, the package `portaudio19-dev` is not needed, because nothing has to be compiled when installing the `sounddevice` module. Only the package `libportaudio2` is needed, as mentioned in https://github.com/spatialaudio/python-sounddevice/issues/74#issuecomment-281079931.

**Comment by Chercas** [comment]
I know that the topic is outdated now. But for those are dealing with it still... I was struggling with this issue as well for a solid two days ( get_default_input_device() works outside conda env but it fails to detect any device while running from inside any of envs). I tried any founded solutions but without result. Then I followed @mgeier and changed conda's libstdc++.so.6 with Ubuntu's one - no result, until I created a copy of base conda's env and figured out that it started to work!!!

**Comment by sameervk** [comment]
I am unable to change conda's libstdc++.so.6 which is in anaconda3/lib/ folder. I am able to copy the file in usr/lib/x86_64-linux-gnu which is of size 1.6 MB and when going to folder anaconda3/lib/ and right-clicking does not give me the paste option. I tried 'sudo cp' but I get the error 'Cannot create regular file: no such file or folder exists'. I have no idea what to do!

**Comment by drammock** [comment]
Here is what worked for me on a laptop running Xubuntu 18.04, with a conda-managed python environment:
```
sudo apt install libportaudio2  # probably it is already installed, but if not this is how to do it
conda install python-sounddevice  # this installed a conda version of portaudio as a dependency
conda uninstall --force portaudio  # the --force flag prevents it from removing sounddevice too
```
after that sounddevice worked normally.

**Comment by asalarian** [comment]
I have the same issue and the solution shown by @drammock worked for me as well. In my case, however, libportaudio2 was already installed on my machine. 
Ubuntu: 19.10
Python: 3.7.5
conda sounddevice package: 0.3.14
conda portaudio package: 19.6.0 (removed after applying the solution)
system libportaudio2: V19.6.0-devel (installed by apt)

**Comment by GoodClover** [comment]
I'm having the same issue, but I never used conda to install anything, I only used pip.
PortAudio version: (1246720, 'PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4')

**Comment by mgeier** [comment]
@GoodClover As always, the questions are:

* Do you have multiple PortAudio libraries on your system? You should look for `libportaudio.so` and similar.
* Which `.so` file is used by the `sounddevice` module? You should check `sd._libname`.
* Do other programs using PortAudio work? You could e.g. try Audacity. You could also try the PyAudio module.

**Comment by yatinarora7** [comment]
> Here is what worked for me on a laptop running Xubuntu 18.04, with a conda-managed python environment:
> 
> ```shell
> sudo apt install libportaudio2  # probably it is already installed, but if not this is how to do it
> conda install python-sounddevice  # this installed a conda version of portaudio as a dependency
> conda uninstall --force portaudio  # the --force flag prevents it from removing sounddevice too
> ```
> 
> after that sounddevice worked normally.

hi there , i am using this on my colab notebook can you suggest something for that.

**Comment by mgeier** [comment]
@yatinarora7 You mean your notebook runs on a server? In this case it won't be of much use if the server plays your sounds in some data center. I guess you should try some JavaScript-based solution?
