### ISSUE TITLE
cffi.api.CDefError: only supports the syntax "#define paUseHostApiSpecificDeviceSpecification ..." (literally)

### ISSUE THREAD

**Issue by josephernest** [spatialaudio/python-sounddevice#80]
`sounddevice` works for me on desktop computer, on RaspberryPi. But here is what happens what I try to use it on a C.H.I.P 9$ computer:

```
chip@chip:~$ python
Python 2.7.9 (default, Aug 13 2016, 17:56:53)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cffi
>>> import sounddevice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sounddevice.py", line 313, in <module>
    """)
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 103, in cdef
    self._parser.parse(csource, override=override, packed=packed)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 166, in parse
    self._internal_parse(csource)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 174, in _internal_parse
    self._process_macros(macros)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 236, in _process_macros
    '%s 0x1FF" for now' % (key, key))
cffi.api.CDefError: only supports the syntax "#define paUseHostApiSpecificDeviceSpecification ..." (literally) or "#define paUseHostApiSpecificDeviceSpecification 0x1FF" for now
```

Any idea? Thanks in advance @spatialaudio !

**Comment by mgeier** [comment]
This looks very much like #49, what CFFI version are you using?

If you install a recent version of the `sounddevice` module (one that has #50 in it, to be exact), a CFFI version of at least 1.0 should be forced, which in turn should avoid your error.

**Comment by josephernest** [comment]
Thanks @mgeier for your answer. How to get the CFFI version and/or install a more recent of sounddevie ?

I did `sudo pip install sounddevice`, I'm using Python 2.7.

**Comment by mgeier** [comment]
```pycon
>>> import cffi
>>> cffi.__version__
```

Use the `--upgrade` flag to, well, upgrade with `pip`.

BTW, who told you to use `sudo`?

**Comment by josephernest** [comment]
Thank you!
